import React, { useRef, useState } from 'react';
import { Alert, Button, Caption, Card, PageHeader, Tag } from '../design-system';

export default function CsvUploadPanel({ onUpload }) {
  const inputRef = useRef(null);
  const [files, setFiles] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState(null);

  function chooseFiles() {
    inputRef.current?.click();
  }

  function selectFiles(event) {
    setFiles(Array.from(event.target.files ?? []));
    setResult(null);
  }

  async function upload() {
    if (!files.length) return;
    setUploading(true);
    setResult(null);
    try {
      setResult(await onUpload(files));
    } catch (error) {
      setResult({ status: 'FAILED', rowsInserted: 0, results: [{ result: 'FAILED', error: error.message }] });
    } finally {
      setUploading(false);
    }
  }

  const tone = result?.status === 'FAILED' ? 'negative' : result?.status === 'NO_NEW_FILES' ? 'warning' : 'positive';

  return (
    <>
      <PageHeader
        title="Card portfolio dashboard"
        lede="Upload local CSV files · analyse imported raw_data"
        meta="Filters apply by applied date and card type; outcomes are shown as Completed or Rejected."
      />
      <Card
        className="csv-upload"
        title="Import CSV files"
        subtitle="Choose one or more local files with status, card_type and applied_date columns."
        headEnd={<Tag>{files.length ? files.length + ' file' + (files.length === 1 ? '' : 's') + ' selected' : 'CSV only'}</Tag>}
      >
        <input ref={inputRef} className="csv-upload__input" type="file" accept=".csv,text/csv" multiple onChange={selectFiles} />
        <div className="csv-upload__actions">
          <Button variant="secondary" onClick={chooseFiles} disabled={uploading}>
            Select CSV files
          </Button>
          <Button variant="primary" onClick={upload} busy={uploading} busyLabel="Importing files" disabled={!files.length}>
            Upload and process
          </Button>
          <Caption>Database IDs are generated by raw_data; do not include an id column in the CSV.</Caption>
        </div>
        {files.length > 0 && (
          <ul className="csv-upload__files" aria-label="Selected CSV files">
            {files.map((file) => (
              <li key={[file.name, file.size, file.lastModified].join(':')}>
                <Tag>{file.name}</Tag>
                <span>{Math.max(1, Math.ceil(file.size / 1024))} KB</span>
              </li>
            ))}
          </ul>
        )}
        {result && (
          <Alert tone={tone} title={result.status === 'NO_NEW_FILES' ? 'No new files to import' : result.status === 'FAILED' ? 'Import failed' : 'Import result'}>
            <p className="csv-upload__result-summary">{result.rowsInserted ?? 0} rows inserted into raw_data.</p>
            <ul className="csv-upload__result-list">
              {result.results.map((item, index) => (
                <li key={(item.filename ?? 'file') + index}>
                  <strong>{item.filename ?? 'Upload'}</strong> · {item.result}
                  {item.rowsInserted ? ' · ' + item.rowsInserted + ' rows' : ''}
                  {item.error ? ' · ' + item.error : ''}
                </li>
              ))}
            </ul>
          </Alert>
        )}
      </Card>
    </>
  );
}
